### ISSUE TITLE
kube-dns

### ISSUE THREAD

**Issue by apurva3000** [projectatomic/atomic-system-containers#132]
I am using Fedora-Atomic-25 image for deploying kubernetes through OpenStack Magnum. It doesn't have kube-dns running by default which is like a default feature now for any kubernetes cluster, afaik. 

I noticed that Fedora-Atomic-25 runs Kubernetes version 1.5 which might be a little older as compared to the recent versions. 

How do I run kube-dns then, is there a newer image which runs kubernetes 1.7+ ?

**Comment by jasonbrooks** [comment]
@apurva3000 kube-dns is always distributed as a container image, so it doesn't come with atomic host. kube-dns comes as part of setting up your cluster. There's more info at https://www.projectatomic.io/blog/2017/09/running-kubernetes-on-fedora-atomic-26/.

Fedora Atomic 26 has kube 1.7 now.

This repo isn't really about the atomic hosts proper, but about system containers that you might run on an atomic host.

**Comment by strigazi** [comment]
FYI, in magnum we use CoreDNS. You can deploy like this:
https://github.com/openstack/magnum/blob/stable/ocata/magnum/drivers/common/templates/kubernetes/fragments/core-dns-service.sh

Note this yaml file has some variables:
DNS_CLUSTER_DOMAIN
PORTAL_NETWORK_CIDR
DNS_SERVICE_IP

Atomic team, do you want to keep this kind of discussion here or redirect people to the openstack means of communication?

#openstack-conrtainers on Freenode
openstack Mailing lists https://wiki.openstack.org/wiki/Mailing_Lists
https://bugs.launchpad.net/magnum

**Comment by apurva3000** [comment]
Thanks a lot for the suggestions, also thanks for pointing me to the right thread.

**Comment by ashcrow** [comment]
> Atomic team, do you want to keep this kind of discussion here or redirect people to the openstack means of communication?

I'll defer to @jasonbrooks

**Comment by jasonbrooks** [comment]
@strigazi If it's a magnum q, I agree that the openstack channels are better for getting help
