### ISSUE TITLE
kubernetes-apiserver needs a writable directory for certificates

### ISSUE THREAD

**Issue by strigazi** [projectatomic/atomic-system-containers#133]
If the user doesn't specify any certificates, the apiserver will try to create those in /var/run/kubernetes or in the directory that is specified with --cert-dir. Currently, all dirs mounted in the apiserver container are read-only.

So, we need to mount /var/run/kubernetes as rw

**Comment by jasonbrooks** [comment]
I actually fixed this in fedora and centos already, I'll send a PR here

**Comment by strigazi** [comment]
Fixed in #134
