### ISSUE TITLE
Services fail bc. service script is lacking executable bit

### ISSUE THREAD

**Issue by neuhalje** [projectatomic/atomic-system-containers#156]
The following scripts lack the x-bit (mode `644`):

* `/var/lib/containers/atomic/kube-scheduler/rootfs/usr/bin/kube-scheduler-docker.sh`
* `/var/lib/containers/atomic/kube-controller-manager/rootfs/usr/bin/kube-controller-manager-docker.sh`
* `/var/lib/containers/atomic/kubelet/rootfs/usr/bin/kubelet-docker.sh`
* `/var/lib/containers/atomic/kube-proxy/rootfs/usr/bin/kube-proxy-docker.sh`

## Images

Images on master:
```text
sudo atomic images list --filter type=ostree

   REPOSITORY                                                     TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE
   registry.fedoraproject.org/f27/kubernetes-proxy                latest   68406693c322   2017-12-10 17:30   237.16 MB      ostree
   registry.fedoraproject.org/f27/kubernetes-kubelet              latest   7c77c5914213   2017-12-10 17:30   241.94 MB      ostree
>  registry.fedoraproject.org/f27/kubernetes-controller-manager   latest   887559c1573c   2017-12-10 17:28   205.33 MB      ostree
>  registry.fedoraproject.org/f27/etcd                            latest   a370ba01d9c3   2017-12-09 11:20   110.78 MB      ostree
```

Images on the node:
```text
sudo atomic images list --filter type=ostree

   REPOSITORY                                          TAG      IMAGE ID       CREATED            VIRTUAL SIZE   TYPE
>  registry.fedoraproject.org/f27/kubernetes-proxy     latest   68406693c322   2017-12-10 17:26   237.16 MB      ostree
>  registry.fedoraproject.org/f27/kubernetes-kubelet   latest   7c77c5914213   2017-12-10 17:25   241.94 MB      ostree
```

**Comment by ashcrow** [comment]
@neuhalje I'm taking a look at this one right now. The files look like they have the execute bit set in repo but on the current latest builds they are missing.

**Comment by ashcrow** [comment]
Looks like the same issue ... a rebuild will and push to the Fedora registry will fix this.

@jasonbrooks PTAL.

**Comment by jasonbrooks** [comment]
Yeah, I fixed these in the fedora repos, but they need to be released. The containers in candidate-registry.fedoraproject.org should have the fix now.

@maxamillion, there wasn't a containers release on the last atomic host release day, was there?

**Comment by neuhalje** [comment]
@jasonbrooks / @maxamillion : Where can I find the next release dates?

**Comment by maxamillion** [comment]
I'm not doing the releases anymore. That's a question for Fedora RelEng

**Comment by ashcrow** [comment]
@maxamillion OK.

All:
We've contacted the currently listed owners of FLIBS to try to pin this down.

/cc @giuseppe

**Comment by giuseppe** [comment]
@ashcrow thanks for looping me in.

**Comment by ashcrow** [comment]
Related: https://pagure.io/releng/issue/7217

**Comment by neuhalje** [comment]
The Fedora releng issue is still "open". 

Is there any way I can help/support in this matter? I am a bit concerned that (at least) two "blocker type" bugs cannot be resolved bc. of a missing release automation.

**Comment by giuseppe** [comment]
@neuhalje do you have an account for commenting on the pagure.io issue?  Otherwise I can refer on the Pagure issue to your comment here

**Comment by neuhalje** [comment]
Seems to be fixed (I created a Pagure account)
