### ISSUE TITLE
Repository Usage Guidance?

### ISSUE THREAD

**Issue by colemickens** [projectatomic/atomic-system-containers#169]
Are these packages published somewhere? Are they the source for the images hosted at `registry.fedoraproject.org`?

I'd like to be able to utilize the very latest available `kubelet` package (preferably even beta releases, but I haven't looked into building a custom RPM yet). I suppose if nothing else I can build my own `kubernetes-kubelet` from here, push it to docker and install via `atomic install`.

**Comment by giuseppe** [comment]
we are still working on automatically building all the system container images to a common place but we are not there yet, we will probably be using quay.io.

@jasonbrooks are you already building the Kubernetes images somewhere that can be used until we complete the automatic build for the entire repository?

**Comment by giuseppe** [comment]
closing this issue for now as this doesn't seem to be happening any time soon
