### ISSUE TITLE
source for registry.centos.org/projectatomic/cri-o:latest

### ISSUE THREAD

**Issue by colemickens** [projectatomic/atomic-system-containers#170]
Where is the source for `registry.centos.org/projectatomic/cri-o:latest`, for example?

**Comment by giuseppe** [comment]
correct, the `registry.centos.org/projectatomic/cri-o:latest` image is built automatically from https://github.com/kubernetes-incubator/cri-o/tree/master/contrib/system_containers/centos:

https://github.com/CentOS/container-index/blob/master/index.d/projectatomic.yaml#L16-L27
