### ISSUE TITLE
atomic uninstall flannel stops docker service

### ISSUE THREAD

**Issue by mike-nguyen** [projectatomic/atomic-system-containers#23]
Running atomic uninstall flannel stops the docker service.  The expected result is that docker would be restarted after the uninstall is completed.

$ sudo atomic install --system --name=flannel gscrivano/flannel
Extracting to /var/lib/containers/atomic/flannel.0
systemctl daemon-reload
systemd-tmpfiles --create /etc/tmpfiles.d/flannel.conf
systemctl enable flannel
$ sudo systemctl start flannel
$ sudo systemctl status flannel
● flannel.service - Flanneld overlay address etcd agent
   Loaded: loaded (/etc/systemd/system/flannel.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-01-09 16:55:04 UTC; 3s ago
  Process: 16527 ExecStartPost=/usr/bin/sh -c while test \! -s /run/flannel/docker; do sleep 0.1; done (code=exited, status=0/SUCCESS)
 Main PID: 16526 (runc)
   CGroup: /system.slice/flannel.service
           └─16526 /bin/runc run flannel

Jan 09 16:55:04 cloud-test-8.localdomain systemd[1]: Starting Flanneld overlay address etcd agent...
Jan 09 16:55:04 cloud-test-8.localdomain runc[16526]: I0109 16:55:04.725491   16542 main.go:275] Installing si...lers
Jan 09 16:55:04 cloud-test-8.localdomain runc[16526]: I0109 16:55:04.725742   16542 main.go:130] Determining I...face
Jan 09 16:55:04 cloud-test-8.localdomain runc[16526]: I0109 16:55:04.727324   16542 main.go:188] Using 192.168...face
Jan 09 16:55:04 cloud-test-8.localdomain runc[16526]: I0109 16:55:04.727348   16542 main.go:189] Using 192.168...oint
Jan 09 16:55:04 cloud-test-8.localdomain runc[16526]: I0109 16:55:04.730836   16542 etcd.go:129] Found lease (...sing
Jan 09 16:55:04 cloud-test-8.localdomain runc[16526]: I0109 16:55:04.731628   16542 etcd.go:84] Subnet lease a...0/24
Jan 09 16:55:04 cloud-test-8.localdomain runc[16526]: I0109 16:55:04.734812   16542 udp.go:222] Watching for n...ases
Jan 09 16:55:04 cloud-test-8.localdomain systemd[1]: Started Flanneld overlay address etcd agent.
Hint: Some lines were ellipsized, use -l to show in full.
$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2017-01-09 16:54:39 UTC; 33s ago
     Docs: http://docs.docker.com
 Main PID: 16392 (docker-current)
   CGroup: /system.slice/docker.service
           └─16392 /usr/bin/docker-current daemon --exec-opt native.cgroupdriver=systemd --selinux-enabled --log-d...

Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364785435Z" level=inf...t."
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364836940Z" level=inf...e."
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364851837Z" level=inf...on"
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364868484Z" level=inf...0.3
Jan 09 16:54:39 cloud-test-8.localdomain systemd[1]: Started Docker Application Container Engine.
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.372550057Z" level=inf...ck"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.510647173Z" level=err...el"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.531907643Z" level=err...el"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.574968422Z" level=inf...0}"
Jan 09 16:54:59 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:59.318968814Z" level=err...el"
Warning: docker.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hint: Some lines were ellipsized, use -l to show in full.
$ sudo systemctl daemon-reload
$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─flannel.conf
   Active: active (running) since Mon 2017-01-09 16:54:39 UTC; 42s ago
     Docs: http://docs.docker.com
 Main PID: 16392 (docker-current)
   CGroup: /system.slice/docker.service
           └─16392 /usr/bin/docker-current daemon --exec-opt native.cgroupdriver=systemd --selinux-enabled --log-d...

Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364785435Z" level=inf...t."
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364836940Z" level=inf...e."
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364851837Z" level=inf...on"
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364868484Z" level=inf...0.3
Jan 09 16:54:39 cloud-test-8.localdomain systemd[1]: Started Docker Application Container Engine.
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.372550057Z" level=inf...ck"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.510647173Z" level=err...el"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.531907643Z" level=err...el"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.574968422Z" level=inf...0}"
Jan 09 16:54:59 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:59.318968814Z" level=err...el"
Hint: Some lines were ellipsized, use -l to show in full.
$ sudo atomic uninstall flannel
systemctl stop flannel
systemctl disable flannel
systemd-tmpfiles --remove /etc/tmpfiles.d/flannel.conf
$ sudo systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2017-01-09 16:55:29 UTC; 3s ago
     Docs: http://docs.docker.com
 Main PID: 16392 (code=exited, status=0/SUCCESS)

Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.364868484Z" level=inf...0.3
Jan 09 16:54:39 cloud-test-8.localdomain systemd[1]: Started Docker Application Container Engine.
Jan 09 16:54:39 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:39.372550057Z" level=inf...ck"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.510647173Z" level=err...el"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.531907643Z" level=err...el"
Jan 09 16:54:50 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:50.574968422Z" level=inf...0}"
Jan 09 16:54:59 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:54:59.318968814Z" level=err...el"
Jan 09 16:55:29 cloud-test-8.localdomain systemd[1]: Stopping Docker Application Container Engine...
Jan 09 16:55:29 cloud-test-8.localdomain docker-current[16392]: time="2017-01-09T16:55:29.578279483Z" level=inf...d'"
Jan 09 16:55:29 cloud-test-8.localdomain systemd[1]: Stopped Docker Application Container Engine.
Hint: Some lines were ellipsized, use -l to show in full.

**Comment by yuqi-zhang** [comment]
It's not the container but rather stopping the flanneld system service that stops docker. This is also the case if flannel was installed on the host (systemctl stop flannel would cause docker to stop as well). Is there a reason for docker to restart on its own when flannel stops?

**Comment by mike-nguyen** [comment]
Docker was running before I installed and uninstalled flannel.  I expected the system to return to its original state.  

If I run atomic uninstall flannel, I can no longer run any atomic commands that deals with containers because the docker service is no longer running.

**Comment by yuqi-zhang** [comment]
That itself is an issue due to the new backends, I have a patch for that so atomic will work even if docker is not running.

Similarly, if docker was running beforehand, and you `dnf install flanneld` -> `systemctl start flanneld` -> `systemctl stop flanneld`, docker would behave the exact same way.

What do you think @giuseppe

**Comment by giuseppe** [comment]
I don't think it is responsibility of the flannel container to restart docker once it is uninstalled, as @yuqi-zhang confirmed, that is the same behaviour with flannel on the host.

Doesn't the same thing happen when you "systemctl stop flannel"?

**Comment by mike-nguyen** [comment]
Yes, the same thing happens when I run `systemctl stop flannel`.  If this is the expected behavior, does red hat's flannel container needs the same "REQUIRED_BY":"docker.service"?

**Comment by giuseppe** [comment]
the "RequiredBy: docker.service" is to avoid that Docker starts before the Flannel service on a reboot

**Comment by ashcrow** [comment]
@giuseppe @mike-nguyen is this still an issue?

**Comment by giuseppe** [comment]
I think it can be closed since it works as Flannel installed on the host
