### ISSUE TITLE
flannel container not working w/ vxlan backend

### ISSUE THREAD

**Issue by jasonbrooks** [projectatomic/atomic-system-containers#28]
I'm able to get the flannel system container working w/ udp, but not with the vxlan backend. Perhaps we need something added to the config.json.template for this? 

Here's what I'm doing:

node 1:

```
node 1:

# atomic install --system gscrivano/etcd
# atomic install --system gscrivano/flannel
# systemctl start etcd
# runc exec etcd etcdctl set /atomic.io/network/config '{"Network":"10.40.0.0/16", "SubnetLen": 24, "Backend": { "Type": "vxlan" } }'
# systemctl start flannel

node 2:

# atomic install --system --set FLANNELD_ETCD_ENDPOINTS=http://10.10.171.92:2379 gscrivano/flannel
# systemctl start flannel
```

Then I try to ping the flannel0 of node 1 from node 2, or vice versa, and I can't ping. With udp backend, it works.

cc @giuseppe

**Comment by giuseppe** [comment]
Are you using NetworkManager?  I see this error when the NetworkManager service is active:
```
Feb 02 12:22:50 atomic-0011.localdomain NetworkManager[16940]: <error> [1486038170.7360] device (flannel.1): Generated connection does not verify: vxlan.remote: property is missing
```

I've tried with the Flannel 0.7 package, but I get the same error, though Flannel 0.7 requires this patch:

https://github.com/projectatomic/atomic-system-containers/pull/29

If I disable NetworkManager then that error disappears.  I am still not able to get vxlan working properly, even if I run it directly on the host, probably some networking issues on my end.

**Comment by giuseppe** [comment]
Closed by: https://github.com/projectatomic/atomic-system-containers/pull/29
