### ISSUE TITLE
atomic uninstall kubelet does not remove flannel, etc.

### ISSUE THREAD

**Issue by jberkus** [projectatomic/atomic-system-containers#86]
To reproduce:

1. install kubelet/kubeadm as system containers per Jbrooks' instructions
2. kubeadm init
3. add flannel as the pod network
4. atomic unininstal kubelet

Result: kubelet system containers go away, but the kubernetes containers running in docker are still there and still running (flannel, kube-proxy, apiserver, etc.).  Further, these will cause issues if the user attempts to re-install containerized kube on the same system.  Restarting docker gets rid of them.

This is not a major issue, obviously.  However, it would be great if there was some way to give users a clean uninstall experience here -- particularly if we can, it makes system containers clearly superior to other methods of installing/removing kubeadm.

**Comment by jasonbrooks** [comment]
I think the missing step here is kubeadm reset?

**Comment by jberkus** [comment]
I'm suggesting that atomic uninstall kubelet should run kubeadm reset.

**Comment by jasonbrooks** [comment]
We could try that -- actually, I need to add the kubeadm system container to this repo. One might use the kubelet system container on a system where there's no kubeadm.
